//#define HIGHLIGHT_BORDER		WINDOW_BORDER_RAISED
//#define HIGHLIGHT_SHADER		"white"
#define MENU_FONT_SIZE			TEXTSIZE_DEFAULT
#define MENU_FONT_COLOR			1 1 1 0.65
#define MENU_LOCKED_COLOR		0.3 0.3 0.3 1
#define HIGHLIGHT_X				248
#define HIGHLIGHT_Y				20
#define HIGHLIGHT_SIZE			(-(HIGHLIGHT_X)) HIGHLIGHT_Y
//#define HIGHLIGHT_COLOR			0.2 0.25 0.35 0.25
//#define A_BUTTON_COLOR			1 1 1 1
//#define HIGHLIGHT_BORDER_COLOR	0.8 0.95 1 0.4

//-------------------------------------
#define ORIGIN_MENU_TREE		54 64
#define ORIGIN_MENU_TITLE		248 64
#define ORIGIN_MENU_TITLE2		248 64
#define ORIGIN_MENU_TITLE3		246 64
#define TREE_COLOR				1 1 1 0.5

#define ORIGIN_BUTTON_BACK		52 438
#define ORIGIN_BUTTON_CONTINUE	508 438

//--------------------------------
#define ORIGIN_CHOICE_X		80
#define ORIGIN_CHOICE1		ORIGIN_CHOICE_X 130
#define ORIGIN_CHOICE2		ORIGIN_CHOICE_X 150
#define ORIGIN_CHOICE3		ORIGIN_CHOICE_X 170
#define ORIGIN_CHOICE4		ORIGIN_CHOICE_X 190
#define ORIGIN_CHOICE5		ORIGIN_CHOICE_X 210
#define ORIGIN_CHOICE6		ORIGIN_CHOICE_X 270
#define ORIGIN_CHOICE7		ORIGIN_CHOICE_X 290
#define ORIGIN_CHOICE8		ORIGIN_CHOICE_X 310
#define ORIGIN_CHOICE9		ORIGIN_CHOICE_X 330

#define ORIGIN_SETTING_X	240
#define ORIGIN_SETTING1		ORIGIN_SETTING_X 130
#define ORIGIN_SETTING2		ORIGIN_SETTING_X 150
#define ORIGIN_SETTING3		ORIGIN_SETTING_X 170
#define ORIGIN_SETTING4		ORIGIN_SETTING_X 190
#define ORIGIN_SETTING5		ORIGIN_SETTING_X 210
#define ORIGIN_SETTING6		ORIGIN_SETTING_X 270
#define ORIGIN_SETTING7		ORIGIN_SETTING_X 290
#define ORIGIN_SETTING8		ORIGIN_SETTING_X 310
#define ORIGIN_SETTING9		ORIGIN_SETTING_X 330

#define ORIGIN_CHOICE_HL_X	54
#define ORIGIN_CHOICE1_HL	ORIGIN_CHOICE_HL_X 128
#define ORIGIN_CHOICE2_HL	ORIGIN_CHOICE_HL_X 148
#define ORIGIN_CHOICE3_HL	ORIGIN_CHOICE_HL_X 168
#define ORIGIN_CHOICE4_HL	ORIGIN_CHOICE_HL_X 188
#define ORIGIN_CHOICE5_HL	ORIGIN_CHOICE_HL_X 208
#define ORIGIN_CHOICE6_HL	ORIGIN_CHOICE_HL_X 268
#define ORIGIN_CHOICE7_HL	ORIGIN_CHOICE_HL_X 288
#define ORIGIN_CHOICE8_HL	ORIGIN_CHOICE_HL_X 308
#define ORIGIN_CHOICE9_HL	ORIGIN_CHOICE_HL_X 328

#define ORIGIN_CHOICE_A_X	60
#define ORIGIN_CHOICE1_A	ORIGIN_CHOICE_A_X 144
#define ORIGIN_CHOICE2_A	ORIGIN_CHOICE_A_X 164
#define ORIGIN_CHOICE3_A	ORIGIN_CHOICE_A_X 184
#define ORIGIN_CHOICE4_A	ORIGIN_CHOICE_A_X 204
#define ORIGIN_CHOICE5_A	ORIGIN_CHOICE_A_X 224
#define ORIGIN_CHOICE6_A	ORIGIN_CHOICE_A_X 284
#define ORIGIN_CHOICE7_A	ORIGIN_CHOICE_A_X 304
#define ORIGIN_CHOICE8_A	ORIGIN_CHOICE_A_X 324
#define ORIGIN_CHOICE9_A	ORIGIN_CHOICE_A_X 344

// ------
#define ORIGIN_CHOICE_X2	360
#define ORIGIN_CHOICE11		ORIGIN_CHOICE_X2 130
#define ORIGIN_CHOICE12		ORIGIN_CHOICE_X2 150
#define ORIGIN_CHOICE13		ORIGIN_CHOICE_X2 170
#define ORIGIN_CHOICE14		ORIGIN_CHOICE_X2 190
#define ORIGIN_CHOICE15		ORIGIN_CHOICE_X2 210
#define ORIGIN_CHOICE16		ORIGIN_CHOICE_X2 270
#define ORIGIN_CHOICE17		ORIGIN_CHOICE_X2 290
#define ORIGIN_CHOICE18		ORIGIN_CHOICE_X2 310
#define ORIGIN_CHOICE19		ORIGIN_CHOICE_X2 330

#define ORIGIN_SETTING_X2	520
#define ORIGIN_SETTING11	ORIGIN_SETTING_X2 130
#define ORIGIN_SETTING12	ORIGIN_SETTING_X2 150
#define ORIGIN_SETTING13	ORIGIN_SETTING_X2 170
#define ORIGIN_SETTING14	ORIGIN_SETTING_X2 190
#define ORIGIN_SETTING15	ORIGIN_SETTING_X2 210
#define ORIGIN_SETTING16	ORIGIN_SETTING_X2 270
#define ORIGIN_SETTING17	ORIGIN_SETTING_X2 290
#define ORIGIN_SETTING18	ORIGIN_SETTING_X2 310
#define ORIGIN_SETTING19	ORIGIN_SETTING_X2 330

#define ORIGIN_CHOICE_HL_X2	334
#define ORIGIN_CHOICE11_HL	ORIGIN_CHOICE_HL_X2 128
#define ORIGIN_CHOICE12_HL	ORIGIN_CHOICE_HL_X2 148
#define ORIGIN_CHOICE13_HL	ORIGIN_CHOICE_HL_X2 168
#define ORIGIN_CHOICE14_HL	ORIGIN_CHOICE_HL_X2 188
#define ORIGIN_CHOICE15_HL	ORIGIN_CHOICE_HL_X2 208
#define ORIGIN_CHOICE16_HL	ORIGIN_CHOICE_HL_X2 268
#define ORIGIN_CHOICE17_HL	ORIGIN_CHOICE_HL_X2 288
#define ORIGIN_CHOICE18_HL	ORIGIN_CHOICE_HL_X2 308
#define ORIGIN_CHOICE19_HL	ORIGIN_CHOICE_HL_X2 328

#define ORIGIN_CHOICE_A_X2	340
#define ORIGIN_CHOICE11_A	ORIGIN_CHOICE_A_X2 144
#define ORIGIN_CHOICE12_A	ORIGIN_CHOICE_A_X2 164
#define ORIGIN_CHOICE13_A	ORIGIN_CHOICE_A_X2 184
#define ORIGIN_CHOICE14_A	ORIGIN_CHOICE_A_X2 204
#define ORIGIN_CHOICE15_A	ORIGIN_CHOICE_A_X2 224
#define ORIGIN_CHOICE16_A	ORIGIN_CHOICE_A_X2 284
#define ORIGIN_CHOICE17_A	ORIGIN_CHOICE_A_X2 304
#define ORIGIN_CHOICE18_A	ORIGIN_CHOICE_A_X2 324
#define ORIGIN_CHOICE19_A	ORIGIN_CHOICE_A_X2 344

// ---
#define ORIGIN_OP1			176 122
#define ORIGIN_OP2			176 262
#define ORIGIN_OP3			456 122
#define ORIGIN_OP4			456 262

// ---
#define ORIGIN_QUAD1_HL		48 96
#define ORIGIN_QUAD2_HL		48 236
#define ORIGIN_QUAD3_HL		328 96
#define ORIGIN_QUAD4_HL		328 236
#define QUAD_SIZE_X			260
#define QUAD_SIZE_Y			140
#define QUAD_SIZE			QUAD_SIZE_X QUAD_SIZE_Y

// ===================== popup preproc =====================

#ifdef PC
	#define BACK_BUTTON_CLOSE								\
			itemDef											\
			{												\
				type			ITEM_TYPE_BUTTON_NO_TEXT	\
				rect			-600 -800 2000 2000 0 0		\
				visible			1							\
				action			{ close self; }				\
			}
#else
	#define BACK_BUTTON_CLOSE \
			PREPROC_SHADER_DRAW( 0 0 0 0, "white", 0 0 0 0 )
#endif

#define PREPROC_POPUP_CHOICE( pp_update, pp_popupname, pp_offset, pp_height, pp_origin, pp_string, pp_setdvar, pp_show ) \
itemDef { \
	type			ITEM_TYPE_BUTTON \
	textscale 		TEXTSIZE_SMALL \
	textstyle 		ITEM_TEXTSTYLE_SHADOWED \
	rect 			pp_offset 110 pp_height 0 0 \
	origin			pp_origin \
	text 			pp_string \
	forecolor		MENU_FONT_COLOR \
	textalign		ITEM_ALIGN_RIGHT \
	textalignx		-101 \
	textaligny		-21 \
	visible 		pp_show; \
	leaveFocus { \
		play "mouse_submenu_over"; \
	}\
	action { \
		exec pp_setdvar; \
		play CHOICE_FOCUS_SOUND; \
		pp_update \
		close GAME_OPTIONS_MENU_NAME"_"pp_popupname; \
	} \
}


#define PREPROC_DVAR_POPUP_CHOICE( pp_itemIndex, pp_action, pp_origin_x, pp_origin_y, pp_string, pp_show ) \
itemDef \
	{ \
		style			WINDOW_STYLE_SHADER \
		type			ITEM_TYPE_HIGHLIGHT \
		rect			(pp_origin_x+(POPUP_ITEM_WIDTH/16)) (pp_origin_y+(POPUP_ITEM_HEIGHT/4)) (POPUP_ITEM_WIDTH-(POPUP_ITEM_HEIGHT/4)) POPUP_ITEM_HEIGHT CHOICE_HORIZONTAL_ALIGN CHOICE_VERTICAL_ALIGN \
		background		"menu_button_backing_highlight" \
		forecolor		MENU_FONT_COLOR \
		visible			when( localVarInt( ui_highlight_popup ) == pp_itemIndex && pp_show ); \
		decoration \
	} \
itemDef { \
	type			ITEM_TYPE_BUTTON \
	text 			pp_string \
	textscale 		TEXTSIZE_SMALL \
	textstyle 		ITEM_TEXTSTYLE_SHADOWED \
	rect 			pp_origin_x pp_origin_y POPUP_ITEM_WIDTH POPUP_ITEM_HEIGHT CHOICE_HORIZONTAL_ALIGN CHOICE_VERTICAL_ALIGN \
	origin			0 4 \
	forecolor		MENU_FONT_COLOR \
	textalign		ITEM_ALIGN_MIDDLE_CENTER \
	textalignx		0 \
	textaligny		0 \
	visible 		when( pp_show ); \
	onFocus { \
		setLocalVarInt ui_highlight_popup pp_itemIndex; \
	} \
	leaveFocus { \
		setLocalVarInt ui_highlight_popup 0; \
		play "mouse_submenu_over"; \
	}\
	action { \
		pp_action \
		play CHOICE_FOCUS_SOUND; \
		close self; \
	} \
}


#define PREPROC_DVAR_POPUP_CHOICE_EX( pp_itemIndex, pp_action, pp_origin_x, pp_origin_y, pp_string, pp_show, pp_extra ) \
itemDef \
	{ \
		style			WINDOW_STYLE_SHADER \
		type			ITEM_TYPE_HIGHLIGHT \
		rect			(pp_origin_x+(POPUP_ITEM_WIDTH/16)) (pp_origin_y+(POPUP_ITEM_HEIGHT/4)) (POPUP_ITEM_WIDTH-(POPUP_ITEM_HEIGHT/4)) POPUP_ITEM_HEIGHT CHOICE_HORIZONTAL_ALIGN CHOICE_VERTICAL_ALIGN \
		background		"menu_button_backing_highlight" \
		forecolor		MENU_FONT_COLOR \
		visible			when( localVarInt( ui_highlight_popup ) == pp_itemIndex && pp_show ); \
		decoration \
	} \
itemDef { \
	type			ITEM_TYPE_BUTTON \
	text 			pp_string \
	textfont		CHOICE_TEXTFONT \
	textscale		TEXTSIZE_SMALL \
	textstyle 		ITEM_TEXTSTYLE_SHADOWED \
	rect 			pp_origin_x pp_origin_y POPUP_ITEM_WIDTH POPUP_ITEM_HEIGHT CHOICE_HORIZONTAL_ALIGN CHOICE_VERTICAL_ALIGN \
	origin			0 4 \
	forecolor		MENU_FONT_COLOR \
	textalign		ITEM_ALIGN_MIDDLE_CENTER \
	textalignx		0 \
	textaligny		0 \
	visible 		when( pp_show ); \
	pp_extra \
	onFocus { \
		setLocalVarInt ui_highlight_popup pp_itemIndex; \
	} \
	leaveFocus { \
		setdvar ui_highlight_popup 0; \
		play "mouse_submenu_over"; \
	}\
	action { \
		pp_action \
		play CHOICE_FOCUS_SOUND; \
		close self; \
	} \
}

